### ISSUE TITLE
change parameters like temperature?

### ISSUE THREAD

**Issue by potaslab** [JuliaML/OpenAI.jl#29]
Is it possible to change the temperature? How could we do that?

**Comment by algunion** [comment]
It is as simple as adding additional keyword arguments.

Here is an example for completion:

```
create_completion(
    ENV["OPENAI_API_KEY"],
    "text-ada-001";
    prompt="Oranges are...",
    temperature=0.5
  )
```
The only exception is for `stream`, where instead of using `stream=true`, you should provide a `streamcallback` function to manage the received chunks (and that, in turn, will set `stream=true`). 

Until we get proper documentation, I also suggest looking at the tests. However, the tests are not showcasing the usage of the additional parameters - so feel free to continue addressing questions here if the basic test examples are not covering something.

**Comment by rory-linehan** [comment]
I'm working on getting Documenter.jl set up now

**Comment by logankilpatrick** [comment]
Done via the docs now: https://juliaml.github.io/OpenAI.jl/dev/
