### ISSUE TITLE
Is there support for v1/completions or only v1/chat/completions?

### ISSUE THREAD

**Issue by potaslab** [JuliaML/OpenAI.jl#30]
Ive tried using models like  "text-ada-001", but I get this error: 

```
{
  "error": {
    "message": "Invalid URL (POST /v1/chat/completions)",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
```

Is there a way to support these models? Do they might need different input parameters?

**Comment by algunion** [comment]
It seems that you used the `create_chat` instead of `create_completion`.

The `/v1/chat/completions` is used for chat (`create_chat`), and it only supports the `gpt-4` and `gpt-3.5-turbo` models.

The correct endpoint for completion is `/v1/completions` (and you need to use `create_completion`).

Here is an example:

```
create_completion(
    ENV["OPENAI_API_KEY"],
    "text-ada-001";
    prompt="Oranges are..."
  )
  ```

**Comment by logankilpatrick** [comment]
See the docs, this package supports both completions and chat completions: https://juliaml.github.io/OpenAI.jl/dev/
